### ISSUE TITLE
Server watchdog kills server due to a possible deadlock

### ISSUE THREAD

**Issue by andriihorpenko** [Low-Drag-MC/Multiblocked2#144]
## Description
I am experiencing multiple server watchdog events with Multiblocked2 stacktrace in each one.
Reproduction steps are unknown to me because this event happens unexpectedly.

## Stacktrace
https://bytebin.lucko.me/rA7D2Pwaz5

**Comment by Yefancy** [comment]
good to know. will check it

**Comment by Yefancy** [comment]
I think I addressed it since 1.0.28.a. but the ae2 maven repo broken. will try to release fixes tmrw

**Comment by andriihorpenko** [comment]
Updated mod on all servers, gonna monitor for a few days. If I don't get back - consider this issue is fixed, thank you 😅

**Comment by andriihorpenko** [comment]
Unfortunately, the issue persists with 1.0.28.a. Attaching a full crash report in case it helps.
[crash-2025-05-27_08.21.13-server.txt](https://github.com/user-attachments/files/20453403/crash-2025-05-27_08.21.13-server.txt)

**Comment by Yefancy** [comment]
interesting. I cannot see which thread is always holding the lock. but it seems that it only happens while the sturcuture was formed but not valid (e.g. chunk initial). I will try to use the `tryLock` instead to see if it got fixed. Before release, I'd lile to send you a build jar for test. I want to release a new version as long as you think it fixed

**Comment by andriihorpenko** [comment]
Sure, you can send a new build here or on Discord

**Comment by Yefancy** [comment]
[multiblocked2-1.20.1-1.0.28.b.zip](https://github.com/user-attachments/files/20453901/multiblocked2-1.20.1-1.0.28.b.zip)

looking forward to your feeback

**Comment by Yefancy** [comment]
any luck?

**Comment by andriihorpenko** [comment]
So far no crashes, I guess we can assume the issue was fixed. If the issue reoccurs - I will let you know here or on Discord.
